name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    # https://github.com/actions/first-interaction
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Salut l'ami, bienvenue sur ton premier signalement"
        pr-message: "Salut l'ami bienvenue sur ton premier pull "
